import type { Metadata } from "next";
import "../globals.css";
import localFont from "next/font/local";
import React from "react";
import ReactQueryProvider from "@/shared/providers/ReactQueryProvider";

const pretendard = localFont({
  src: '../../../public/fonts/PretendardVariable.woff2',
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Nomadly",
  description: "Generated by create next app",
  other: {
    viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover',
  }
};

export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${pretendard.variable} antialiased overflow-x-hidden`}>
    <div className="min-h-[100dvh] min-w-[100dvw] flex flex-col pb-[env(safe-area-inset-bottom)]"> {/* ✅ vh 대신 dvh 사용 */}
      <main className="flex-1 flex w-full h-full">
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </main>
    </div>
    </body>
    </html>
  );
}
