import type { Metadata } from "next";
import "../../globals.css";
import localFont from "next/font/local";
import React from "react";
import BottomNav from "@/shared/components/layout/BottomNav";
import ReactQueryProvider from "@/shared/providers/ReactQueryProvider";

const pretendard = localFont({
  src: '../../../../public/fonts/PretendardVariable.woff2',
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover',
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased overflow-x-hidden`}>
        <div className="min-h-[100dvh] max-h-[100dvh] min-w-[100dvw] flex flex-col"> {/* ✅ vh 대신 dvh 사용 */}
          <main className="h-[calc(100dvh-calc(4rem+env(safe-area-inset-bottom)))] flex w-full overflow-y-auto">
            <ReactQueryProvider>
            {children}
            </ReactQueryProvider>
          </main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
