import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import React from "react";
import BottomNav from "@/shared/components/BottomNav";

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
