import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import React from "react";
import BottomNav from "@/shared/components/BottomNav";

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased overflow-x-hidden`}>
        <div className="min-h-[100dvh] min-w-[100dvw] flex flex-col"> {/* ✅ vh 대신 dvh 사용 */}
          <main className="flex-1 flex w-full h-full">{children}</main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
